name: worldcup-winner-predictor-env
dependencies:
  - python=3.8.15
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - plotly
    - scikit-learn==1.1.3
    - torch
    - ipykernel
    - openpyxl
    - beautifulsoup4
    - lxml
    - emoji
    - emoji-country-flag
    - pre-commit
    - black
    - xgboost

